Models/Enum/BookingType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Transport.WEB.Models.Enum
{
    public enum BookingType
    {
        Terminal = 0,
        Advanced = 1,
        Online = 2,
        All = 3,
        BookOnHold = 4,
        Agent = 5
    }


    public enum FareType
    {
        Discount = 0,
        Increase = 1
    }

    public enum FareAdjustmentType
    {
        Value = 0,
        Percentage = 1
    }
    public enum FareParameterType
    {
        Route = 0,
        Terminal = 1
    }

}

Models/Transload.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Transport.WEB.Models.Enum;

namespace Transport.WEB.Models
{
    public class Transload
    {
        //public int TerminalId { get; set; }
        //public int RouteId { get; set; }
        //public int TripId { get; set; }
        //public int VehicleId { get; set; }
        //public int DriverId { get; set; }
        public Guid JourneyManagementId { get; set; }
        public Guid VehicleTripRegistrationId { get; set; }
        public string PilotCode { get; set; }
        public decimal? Amount { get; set; }
        public DateTime JourneyDate { get; set; }
        public VehicleStatus VehicleStatus { get; set; }
        public string TransloadedPilot { get; set; }
        public string TransloadedVehicle { get; set; }
        public string PhysicalBusRegistrationNumber { get; set; }
        public string Email { get; set; }
        public string TransloadedBy { get; set; }
        public string NewPilot { get; set; }
        public string NewVehicle { get; set; }
        public JourneyType TransloadedJourneyType { get; set; }
        public string TransloadJourneyType => TransloadedJourneyType.ToString();
        public JourneyType NewJourneyType { get; set; }
        public string NwJourneyType => NewJourneyType.ToString();
        public string Route { get; set; }
        public string NewPilots { get; set; }
        public string TransloadedPilots { get; set; }
        public int TransloadTerminal { get; set; }
        public decimal? NewDriverFee { get; set; }
    }
}

Areas/Admin/Controllers/ReportController.cs
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Transport.WEB.Models;
using Transport.WEB.Models.Enum;
using Transport.WEB.Utils;
using Transport.WEB.Utils.Alerts;
using Transport.WEB.Utils.Helpers;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Transport.WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ReportController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly ILogger _logger;
        private IHostingEnvironment _hostingEnvironment;

        public ReportController(IHttpClientFactory httpClientFactory, ILogger<ReportController> logger, IHostingEnvironment hostingEnvironment)
        {
            _httpClientFactory = httpClientFactory;
            _logger = logger;
            _hostingEnvironment = hostingEnvironment;
        }

        public async Task<IActionResult> Index(int PageIndex = 1,
         int PageSize = 10, int? TerminalId = null, DateTime? StartDate = null, DateTime? EndDate = null)
        {

            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);
            await FetchRequiredDropDowns(departureTerminal: TerminalId.HasValue ? TerminalId : 0);

            ViewBag.StartDate = StartDate;
            ViewBag.EndDate = EndDate;
            ViewBag.Terminal = TerminalId;

            BookingReportQueryModel query = new BookingReportQueryModel
            { StartDate = StartDate ?? DateTime.Now.Date, EndDate = EndDate ?? DateTime.Now, PageIndex = PageIndex, PageSize = PageSize, TerminalId = TerminalId };

            var response = await client.PostAsJsonAsync<BookingReportQueryModel, List<BookingReportModel>>($"{Constants.ClientRoutes.BookingReports}", query);
            ViewBag.TotalCount = response?.Object?.FirstOrDefault()?.TotalCount ?? 0;
            ViewBag.TotalPages = response?.Object?.FirstOrDefault()?.TotalCount / query.PageSize;

            if (response?.Object?.FirstOrDefault()?.TotalCount % query.PageSize > 0) ViewBag.TotalPages++;
            var items = response.Object ?? new List<BookingReportModel> { };

            ViewBag.Page = query.PageIndex;

            if (response.ValidationErrors.Count() > 0)
            {
                return View(items).WithWarning(response.Code + ": " + response.ShortDescription);
            }
            return View(items).WithSuccess(response.ShortDescription);
        }

        [HttpPost]
        public IActionResult Index(BookingReportQueryModel query)
        {
            if (!ModelState.IsValid)
                return Redirect("Index");

            ViewBag.StartDate = query.StartDate;
            ViewBag.EndDate = query.EndDate;
            ViewBag.Terminal = query.TerminalId;

            return RedirectToAction("Index", new { terminalId = query.TerminalId, query.StartDate, query.EndDate });
        }

        [HttpPost]
        public async Task<IActionResult> BookingTrips(BookedTripsQueryModel query)
        {
            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);
            int? vTermId = query.TerminalId;


            //if (!ModelState.IsValid)
            //    return Redirect("Index");

            query.EndDate = query.EndDate ?? DateTime.Now;
            query.StartDate = query.StartDate ?? DateTime.Now.Date;

            ViewBag.StartDate = query.StartDate;
            ViewBag.EndDate = query.EndDate;
            ViewBag.PhysicalBusRegisterationNumber = query.PhysicalBusRegisterationNumber;
            ViewBag.BookingType = query.BookingType;
            ViewBag.IsPrinted = query.IsPrinted;
            ViewBag.DepartureTerminal = query.DepartureTerminalId;
            await FetchRequiredDropDownsForTrips(vehicleRegistrationNumber: query.PhysicalBusRegisterationNumber ?? "");

            var response = await client.PostAsJsonAsync<BookedTripsQueryModel, List<BookedTripsModel>>($"{Constants.ClientRoutes.BookedTrips}", query);

            IEnumerable<BookedTripsModel> items = null;
            if (vTermId.HasValue && vTermId != 0)
            {
                var vitems = response.Object ?? new List<BookedTripsModel> { };
                items = vitems.Where(x => x.DepartureTerminal == vTermId && x.IsPrinted.Equals(true));
            }
            else
            {
                items = response.Object ?? new List<BookedTripsModel> { };
            }
            if (response.ValidationErrors.Count() > 0)
            {
                return View(items).WithWarning(response.Code + ": " + response.ShortDescription);
            }
            return View(items).WithSuccess(response.ShortDescription);
        }
        [HttpGet]
        public async Task<IActionResult> BookingTrips()
        {
            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);

            var query = new BookedTripsQueryModel
            {
                PhysicalBusRegisterationNumber = null,
                BookingType = null,
                EndDate = DateTime.Now,
                StartDate = DateTime.Now.Date,
                IsPrinted = true,
                DepartureTerminalId = null
            };
            await FetchRequiredDropDownsForTrips(vehicleRegistrationNumber: query.PhysicalBusRegisterationNumber ?? null);
            var response = await client.PostAsJsonAsync<BookedTripsQueryModel, List<BookedTripsModel>>($"{Constants.ClientRoutes.BookedTrips}", query);
            var items = response.Object = new List<BookedTripsModel> { };

            if (response.ValidationErrors.Count() > 0)
            {
                return View(items).WithWarning(response.Code + ": " + response.ShortDescription);
            }
            return View(items).WithSuccess(response.ShortDescription);
        }


        [HttpGet]
        public async Task<IActionResult> BookingSales(int? TerminalId = null, DateTime? StartDate = null, DateTime? EndDate = null)
        {
            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);

            var query = new BookingSalesReportQueryModel
            {
                EndDate = DateTime.Now,
                StartDate = DateTime.Now.Date
            };


            var response = await client.PostAsJsonAsync<BookingSalesReportQueryModel, List<BookingSalesReportModel>>($"{Constants.ClientRoutes.BookedSales}", query);
            var items = response.Object = new List<BookingSalesReportModel> { };
            await FetchRequiredDropDowns();

            if (response.ValidationErrors.Count() > 0)
            {
                return View(items).WithWarning(response.Code + ": " + response.ShortDescription);
            }

            return View(items).WithSuccess(response.ShortDescription);
        }
        [HttpPost]
        public async Task<IActionResult> BookingSales(BookingSalesReportQueryModel query)
        {
            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);
            if (!ModelState.IsValid)
            {
                await FetchRequiredDropDowns(state: query.StateId, route: query.RouteId, departureTerminal: query.TerminalId);
                return View();
            }
            if (query == null)
                query = new BookingSalesReportQueryModel { StartDate = DateTime.Now.Date, EndDate = DateTime.Now };

            ViewBag.StartDate = query.StartDate ?? DateTime.Now.Date;
            ViewBag.EndDate = query.EndDate ?? DateTime.Now;
            ViewBag.CreatedBy = query.CreatedBy;

            await FetchRequiredDropDowns(state: query.StateId, route: query.RouteId, departureTerminal: query.TerminalId);
            var response = await client.PostAsJsonAsync<BookingSalesReportQueryModel, List<BookingSalesReportModel>>($"{Constants.ClientRoutes.BookedSales}", query);

            var items = response.Object ?? new List<BookingSalesReportModel> { };

            if (response.ValidationErrors.Count() > 0)
            {
                return View(items).WithWarning(response.Code + ": " + response.ShortDescription);
            }
            return View(items).WithSuccess(response.ShortDescription);
        }

        [HttpGet]
        public async Task<IActionResult> PassengerReport(string keyword = null)
        {
            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);
            var query = new PassengerReportQueryModel
            {
                EndDate = DateTime.Now,
                StartDate = DateTime.Now.Date
            };
            var response = await client.PostAsJsonAsync<PassengerReportQueryModel, List<PassengerReportModel>>($"{Constants.ClientRoutes.PassengerReport}", query);
            var items = response.Object ?? new List<PassengerReportModel> { };

            if (response.ValidationErrors.Count() > 0)
            {
                return View(items).WithWarning(response.Code + ": " + response.ShortDescription);
            }
            return View(items).WithSuccess(response.ShortDescription);
        }

        [HttpPost]
        public async Task<IActionResult> PassengerReport(PassengerReportQueryModel query)
        {
            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);
            if (!ModelState.IsValid)
            {
                return View();
            }

            query.EndDate = query.EndDate ?? DateTime.Now;
            query.StartDate = query.StartDate ?? DateTime.Now.Date;

            ViewBag.StartDate = query.StartDate;
            ViewBag.EndDate = query.EndDate;

Areas/Admin/Views/Report/EditGeneralTransaction.cshtml
@model GeneralTransactionDTO
@{
    ViewData["Title"] = "EditGeneralTransaction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit General Transaction</h2>

<div class="m-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="m-portlet">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <span class="m-portlet__head-icon m--hide">
                                <i class="la la-gear"></i>
                            </span>
                            <h3 class="m-portlet__head-text">
                                Edit Transactions
                            </h3>
                        </div>
                        <div class="col-lg-4"></div>
                        <div class="col-lg-4">
                            <div class="m-portlet__head-tools">
                                <ul class="m-portlet__nav">
                                    <li class="m-portlet__nav-item">
                                        <a href="~/admin/report/GeneralTransaction" class="btn btn-success m-btn m-btn--pill m-btn--icon m-btn--air">
                                            <span>
                                                <i class="la la-search"></i>
                                                <span>View All General Transaction</span>
                                            </span>
                                        </a>
                                    </li>
                                    <li class="m-portlet__nav-item"></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                @using (Html.BeginForm("PostEditGeneralTransaction", "Report", FormMethod.Post, new { @class = "m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" }))
                {
            <div class="m-form__section m-form__section--first">

                <div class="form-group m-form__group row">
                    <label class="col-lg-2 col-form-label">Transaction Amount :</label>
                    <div class="col-lg-6">
                        <input type="hidden" asp-for="id" />
                        <input class="form-control m-input dropdown-select2" asp-for="TransactionAmount" />
                        <div class="form-control-feedback"><span asp-validation-for="TransactionAmount"></span></div>
                    </div>
                </div>
                <div class="form-group m-form__group row">
                    <label class="col-lg-2 col-form-label">Transaction Type :</label>
                    <div class="col-lg-6">
                        <select id="trantype" asp-for="TransactionType" class="form-control m-input dropdown-select2 sts" asp-items="@(Html.GetEnumSelectList<TransactionType>().Where(x => x.Text.Contains("Debit") ||  x.Text.Contains("Credit")))">
                            <option value="">Select</option>
                        </select>
                        <div class="form-control-feedback"><span asp-validation-for="TransactionType"></span></div>
                    </div>
                </div>
                <div class="form-group m-form__group row">
                    <label class="col-lg-2 col-form-label"> Pay Type Discription : </label>
                    <div class="col-lg-6">
                        <select id="paydescription" asp-for="PayTypeDiscription" class="form-control m-input dropdown-select2 sts" asp-items="@(Html.GetEnumSelectList<PayTypeDescription>().Where(x =>
                                    x.Text.Contains("Bonus") ||
                                    x.Text.Contains("Fine")||
                                    x.Text.Contains("Lateness") ||
                                    x.Text.Contains("DrunkDriving") ||
                                    x.Text.Contains("Recklesness") ||
                                    x.Text.Contains("SalaryPayment") ||
                                    x.Text.Contains("MTU") ||
                                    x.Text.Contains("Part") ||
                                    x.Text.Contains("Transload") ||
                                    x.Text.Contains("Loan")
                                    ))">
                            <option value="">Select</option>
                        </select>
                        <div class="form-control-feedback"><span asp-validation-for="PayTypeDiscription"></span></div>
                    </div>
                </div>
                <div class="form-group m-form__group row">
                    <label class="col-lg-2 col-form-label" for="TransactionDate">Transaction Date:</label>
                    <div class="col-lg-6">
                        <input class="form-control m-input" asp-for="TransactionDate" placeholder="dd/mm/yyyy">
                        <div class="form-control-feedback"><span asp-validation-for="TransactionDate"></span></div>
                    </div>
                </div>
                <div class="form-group m-form__group row">
                    <label class="col-lg-2 col-form-label">Notes :</label>
                    <div class="col-lg-6">
                        @Html.TextAreaFor(m => m.TransDescription, new { @class = "form-control", id = "note", placeholder = "Enter Notes", rows = "4" })
                        <div class="form-control-feedback"><span asp-validation-for="TransDescription"></span></div>
                    </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <label class="col-lg-2 col-form-label"> Is Active : </label>
                        <div class="col-lg-6">
                            <select class="form-control dropdown-select2" asp-for="IsActive">
                                <option value="false">No</option>
                                <option value="true">Yes</option>
                            </select>
                            <div class="form-control-feedback"><span asp-validation-for="IsActive"></span></div>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-primary m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air" id="btnsubmit"><i class="la la-search"></i> Update </button>
                        </div>
                        </div>
            </div>
                }
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js"></script>
    <script>

    </script>
}

Areas/Admin/Views/Report/GetMtuById.cshtml
@model MtuReportModelDTO
@{
    ViewData["Title"] = "View Patrol Reports";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@{
    ViewData["Title"] = "View More";
}
@section Styles
{
    <style>
        img {
            border: 1px solid #ddd; /* Gray border */
            border-radius: 4px; /* Rounded border */
            padding: 5px; /* Some padding */
            width: 80px;
            height: 60px;/* Set a small width */
        }

            /* Add a hover effect (blue shadow) */
            img:hover {
                box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
            }
    </style>
}
<h3>View More</h3>
<div class="m-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="m-portlet">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <span class="m-portlet__head-icon m--hide">
                                <i class="la la-gear"></i>
                            </span>
                            <h3 class="m-portlet__head-text">
                                View Report
                            </h3>
                        </div>
                        <div class="col-lg-4"></div>
                        <div class="col-lg-4">
                            <div class="m-portlet__head-tools">
                                <ul class="m-portlet__nav">
                                    <li class="m-portlet__nav-item">
                                        <a href="~/admin/report/GetReports" class="btn btn-success m-btn m-btn--pill m-btn--icon m-btn--air">
                                            <span>
                                                <i class="la la-search"></i>
                                                <span>Search Reports</span>
                                            </span>
                                        </a>
                                    </li>
                                    <li class="m-portlet__nav-item"></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                @using (Html.BeginForm("MtuReports", "Report", FormMethod.Get, new { @class = "m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" }))
                {
                    <div class="m-form__section m-form__section--first">

                        <div class="form-group m-form__group row">
                            <label class="col-lg-2 col-form-label" for="VehicleModelId">Vehicle :</label>
                            <div class="col-lg-6">
                                <input class="form-control m-input dropdown-select2" disabled readonly asp-for="RegistrationNumber" />
                                <div class="form-control-feedback"><span asp-validation-for="RegistrationNumber"></span></div>
                            </div>
                        </div>
                        <div class="form-group m-form__group row">
                            <label class="col-lg-2 col-form-label" for="DriverId">Driver :</label>
                            <div class="col-lg-6">
                                <input class="form-control" readonly disabled asp-for="DriverCode" />
                                <div class="form-control-feedback"><span asp-validation-for="DriverCode"></span></div>
                            </div>
                        </div>
                        <div class="form-group m-form__group row">
                            <label class="col-lg-2 col-form-label" for="DriverId">Vehicle Status :</label>
                            <div class="col-lg-6">
                                <input class="form-control m-input dropdown-select2" disabled readonly asp-for="Status" />
                                <div class="form-control-feedback"><span asp-validation-for="Status"></span></div>
                            </div>
                        </div>
                        <div class="form-group m-form__group row">
                            <label class="col-lg-2 col-form-label" for="Picture">Picture:</label>
                            <div class="col-lg-6">
                                <div class="m--align-center form-group">
                                    <div class="row">
                                        @if (Model.MtuPhotos.Count == 0)
                                        {
                                            <p>&nbsp; &nbsp; &nbsp;</p><label>There are no Images for this Report</label>
                                        }
                                        @foreach (var item in Model.MtuPhotos)
                                        {
                                            <p>&nbsp; &nbsp; &nbsp;</p><a target="_blank" href="~/images/mtureports/@item.FileName">
                                                <img src="~/images/mtureports/@item.FileName" alt="Avatar" class="m--align-center avatar" id="avartarId">
                                            </a>
                                        }
                                    </div>
                                </div>
                                <div class="form-control-feedback"><span asp-validation-for="Picture"></span></div>
                            </div>
                        </div>
                        <div class="form-group m-form__group row">
                            <label class="col-lg-2 col-form-label" for="DriverId">Notes :</label>
                            <div class="col-lg-6">
                                @Html.TextAreaFor(m => m.Notes, new { @class = "form-control m-input dropdown-select2", rows = "4", @readonly = "readonly", disabled = "disabled" })
                                <div class="form-control-feedback"><span asp-validation-for="Notes"></span></div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js"></script>
    <script>
                //$(document).ready(function () {
                //    $(".dropdown-select2").select2();
                //});

                //var No = $('#Id').val();

                //$(document).on("click", "#view", function () {
                //    $("#view").hide();

                //    $.getJSON("/admin/report/getmtubyid/?Id=" + No,

                //        function (data) {
                //            console.log(data)
                //            if (data.picture != null)
                //                $("#avartarId").attr("src", data.picture);
                //        });
                //});

    </script>
}

Areas/Admin/Views/Report/JourneyDetailReport.cshtml
@model IEnumerable<JourneyDetailDisplayDTO>
@{
    ViewData["Title"] = "JourneyDetailReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //var journeyType = (string)ViewBag.journeyType;
}

<h2>JourneyDetailReport</h2>

<div class="m-alert m-alert--icon m-alert--air m-alert--square alert alert-dismissible m--margin-bottom-30" role="alert">
    <div class="m-alert__icon">
        <i class="flaticon-exclamation m--font-brand"></i>
    </div>
    <div class="m-alert__text">
        Terminal  Journey Details.
    </div>
</div>

<div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    Terminal @ViewBag.journeyType Details
                </h3>
            </div>
        </div>
        @*<div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="~/admin/report/blow" class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                        <span>
                            <i class="la la-plus"></i>
                            <span>Blow Another Vehicle</span>
                        </span>
                    </a>
                </li>
                <li class="m-portlet__nav-item"></li>
            </ul>
        </div>*@
    </div>
    @*<div class="m-portlet__body">
            <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Phone Number</th>
                        <th>Destination</th>
                        <th>Vehicle Number</th>
                    </tr>
                </thead>
            </table>
            @Html.AntiForgeryToken()
        </div>*@
    <div class="m-portlet__body">
        <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
            <thead>
                <tr>
                    <th>Bus Number</th>
                    <th>Driver Code</th>
                    <th>Driver Name</th>
                    <th>Route</th>
                    @*<th>Blow Date</th>*@
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                <tr>
                    <th>@item.PhysicalBusRegistrationNumber</th>
                    <th>@item.DriverCode</th>
                    <th>@item.DriverName</th>
                    <th>@item.Name</th>
                </tr>
                }
            </tbody>
        </table>
        @Html.AntiForgeryToken()
    </div>
</div>

@section Scripts {

    <script src="~/lib/datatables.bundle.js"></script>
    <script src="~/lib/jsrender/jsrender.min.js"></script>
    <script src="~/lib/blockUI/jquery.blockUI.js"></script>
    <script src="~/lib/toastr/toastr.js"></script>

    @*<script>  
        $(document).on("click", "#btnsearch", function () {
            // var url = "/terminals/booking/destination/" + departureTerminalId;// +"?callback=?";
            $('#btnsearch').attr('disabled', true);
            var startdate = $('#StartDate').val();
            var enddate = $('#EndDate').val();
            $("#m_table_1").DataTable({
                responsive: !0,
                processing: !0,
                serverSide: !0,
                ajax: '../../admin/report/getblowndata/?startdate=' + startdate + '&enddate=' + enddate,
                columns: [
                    {
                        bSortable: false,
                        data: "physicalBusRegistrationNumber"
                    },
                    {
                        bSortable: false,
                        data: "driverCode"
                    },
                    {
                        bSortable: false,
                        data: "routeName"
                    }
                ],
                lengthMenu: [25, 50, 100, 200],
                pageLength: 50,
                language: {
                    lengthMenu: "Display _MENU_"
                },
                headerCallback: function (e, a, t, n, s) {
                    e.getElementsByTagName("th")[0].innerHTML = '\n<label class="m-checkbox m-checkbox--single m-checkbox--solid m-checkbox--brand">\n <input type="checkbox" value="" class="m-group-checkable">\n <span></span>\n </label>'
                },
                order: []
            });
        });

        var exportbookingreportToExcel = function () {
            $("#sloader").show();
            var data = $("#SubmitFormM").serialize();
            var date = $("#StartDate").val();
            var enddate = $("EndDate").val();

            window.location = "../../admin/report/exportCustDetails/?startdate=" + date;
            //$.ajax({
            //    type: "Post",
            //    url: "../../admin/report/exportCustDetails/?startdate=" + date,
            //    data: data,
            //    success: function (data) {
            //        //alert("Success!..");
            //        console.log(data);
            //        swal('Your File has been Exported Successfully');
            //        //$("#MyModal").modal("hide");
            //    }

            //})
            $("#sloader").hide();
        };


    </script>*@

}